GENERAL:
    #GPU_ID: "0"
    #GPU_ID: "1"
    #GPU_ID: "2"
    GPU_ID: "3"
    #GPU_ID: "4"
    #GPU_ID: "5"
    #GPU_ID: "6"

BASIC:
    #MODEL_SAVE_PERIOD: 1
    #MODEL_SAVE_PERIOD: 10
    MODEL_SAVE_PERIOD: 50
    #MODEL_SAVE_PERIOD: 500000
    #PREDICTION_PERIOD: 1
    PREDICTION_PERIOD: 5
    #PREDICTION_PERIOD: 10

MODEL:
    ARCHITECTURE: "A2C"
    BATCH_SIZE: 100
    GAMMA: 0.95
    #GAMMA: 0.99
    NUM_EPISODES: 1000
    #K: 2 
    K: 4
    #K: 5

ACTOR:
    ACTOR_LR: 0.0001

CRITIC:
    CRITIC_LR: 0.002

ENV:
    OPT_LR: 0.01
    OPT_ITER: 5
    #REWARD_SCALE: 0.2
    REWARD_SCALE: 0.33
    #REWARD_SCALE: 0.5
    REWARD_FACTOR: 100
    #STEP_LIMIT: 20
    STEP_LIMIT: 24
    #STEP_LIMIT: 50
    EPSILON: 0.001

DATA:
    #TARGET_OFFSET: 0.0
    TARGET_OFFSET: {"other": 0.3}
    #TARGET_OFFSET: {"param_01": "pi", "other": 0.3}
    #TARGET_PARAMS_TO_OFFSET: "all_pose"
    TARGET_PARAMS_TO_OFFSET: "all_pose_and_global_rotation"
    
    #PARAM_OFFSET: 0.0
    PARAM_OFFSET: {"other": 0.3}
    #PARAMS_OFFSET: {"param_01": "pi", "other": 0.3}
    #PARAMS_TO_OFFSET: "all_pose"
    PARAMS_TO_OFFSET: "all_pose_and_global_rotation"

